[package]
name = "engine"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Minimal procedural 3D engine (wgpu)"

[lints]
workspace = true

[dependencies]
bytemuck = { workspace = true }
egui = { workspace = true }
egui-wgpu = { workspace = true }
egui-winit = { workspace = true }
glam = { workspace = true }
gltf = { workspace = true }
image = { workspace = true }
noise = { workspace = true }
pollster = { workspace = true }
rayon = { workspace = true }
rodio = { workspace = true }
thiserror = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }
